### ISSUE TITLE
Discussion and Future Work Chapter Review

### ISSUE THREAD

**Issue by hayleepierce** [ReadyResearchers-2023-24/cis-600-f2023-610-s2024-senior-thesis-simojo#11]
None of the papers I've looked at contained a Discussion chapter, nor does the template, so I'm not sure what I'm supposed to look at for that part of the review. However, your Future Work Chapter is written well and is easy to understand. Some more details about what the future work entails and how it would benefit the project would be useful. Overall, your writing is excellent and flows well. I think you are in a good position to edit and finish your thesis. Good luck!

**Comment by simojo** [comment]
Thanks Haylee!
