### ISSUE TITLE
Feedback on thesis

### ISSUE THREAD

**Issue by jjumadinova** [ReadyResearchers-2023-24/cis-600-f2023-610-s2024-senior-thesis-simojo#13]
@simojo, below are suggestions for improvement of your thesis:

- Typically, research paper's abstract does not contain citations.
- Rewrite Goals of the Project subsection from the completed project perspective.
- Restructure Theory section in Method chapter by breaking it up into algorithmic and sensor subsections.
- Chapter 4 needs to have a section called "Threats to Validity".
- Chapter 5 needs to include discussion of the impact of completed work and critical reflection on the project.
- GitHub Actions is not running in the writing repository.
- Revisit your artifact's README. Specifically, delete Table of Contents, rephrase Abstract as Overview, and delete all References except for the ones cited in Overview.

**Comment by simojo** [comment]
- [x] Typically, research paper's abstract does not contain citations.
- [ ] Rewrite Goals of the Project subsection from the completed project perspective.
- [ ] Restructure Theory section in Method chapter by breaking it up into algorithmic and sensor subsections.
- [ ] Chapter 4 needs to have a section called "Threats to Validity".
- [ ] Chapter 5 needs to include discussion of the impact of completed work and critical reflection on the project.
- [x] GitHub Actions is not running in the writing repository.
- [ ] Revisit your artifact's README. Specifically, delete Table of Contents, rephrase Abstract as Overview, and delete all References except for the ones cited in Overview.
