### ISSUE TITLE
Peer Review: Thesis Chapters Simon Jones

### ISSUE THREAD

**Issue by PCain02** [ReadyResearchers-2023-24/cis-600-f2023-610-s2024-senior-thesis-simojo#5]
Overall, I think there is a very good flow to your paper and you provide extremely helpful visuals. I can tell you have done extensive background research on the subject. The flow is very clear and I appreciate how you explain the importance of all the different aspects of the UAV. The motivation for the project is very clear. I will say when summarizing your project in class you talked about the affordability of sensors being an important aspect of your project, but I found that was only mentioned once in these chapters. I appreciated the visuals a lot and I think they are very helpful when explaining your work in the realms of software and hardware. I am super interested in the Gazebo software and I think it would be great if you included more!

The main way I think these sections could be improved is by adding more information and balancing the information. Sometimes it felt like certain sections had a lot of detail and others felt like it could use more. Additionally, I think there could be more explanation for the mathematical sections. It did not feel very accessible to read through the mathematical parts. For example, the matrix on page 16 felt thrown in with little explanation of what a rotational matrix is or why it is important. Page 17 also feels like it could be reworked to be more accessible to people from focuses other than math or physics. The 'Laser Basics' section is well done in that regard. 

Ultimately, I think you did an excellent job on these chapters and I am looking forward to seeing more!

I make some more specific comments here (sadly half of them got deleted, I tried to remember as much as possible): [Link](https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:907ae0dc-0e07-3872-b433-f31f43ad9309 )

**Comment by simojo** [comment]
Thanks for the feedback!
